'use client';
import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { payrollLocationView, type PayrollReportRow } from '@/lib/payroll-report';

type Row=PayrollReportRow;
type Summary={employees:number;gross_hours:number;break_hours:number;payable_hours:number;rounded_hours:number;cheque_hours:number;cash_hours:number;cheque_pay:number;cash_pay:number;total_pay:number};
const empty:Summary={employees:0,gross_hours:0,break_hours:0,payable_hours:0,rounded_hours:0,cheque_hours:0,cash_hours:0,cheque_pay:0,cash_pay:0,total_pay:0};
const control:React.CSSProperties={background:'#141a24',border:'1px solid rgba(255,255,255,.12)',borderRadius:7,color:'#e5e7eb',padding:'7px 10px',fontSize:12,outline:'none'};
const money=(value:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(value||0);
function initialPeriod(){const now=new Date();if(now.getDate()<=15){const previous=new Date(now.getFullYear(),now.getMonth()-1,1);return{month:`${previous.getFullYear()}-${String(previous.getMonth()+1).padStart(2,'0')}`,period:'16-end'};}return{month:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,period:'1-15'};}
function dates(month:string,period:string){const[y,m]=month.split('-').map(Number);const last=new Date(y,m,0).getDate();return{start:`${month}-${period==='16-end'?'16':'01'}`,end:`${month}-${period==='1-15'?'15':String(last).padStart(2,'0')}`};}
function summarize(rows:Row[]):Summary{return rows.reduce((sum,row)=>({employees:sum.employees+1,gross_hours:sum.gross_hours+row.gross_hours,break_hours:sum.break_hours+row.break_hours,payable_hours:sum.payable_hours+row.payable_hours,rounded_hours:sum.rounded_hours+row.rounded_hours,cheque_hours:sum.cheque_hours+row.cheque_hours,cash_hours:sum.cash_hours+row.cash_hours,cheque_pay:sum.cheque_pay+row.cheque_pay,cash_pay:sum.cash_pay+row.cash_pay,total_pay:sum.total_pay+row.total_pay}),{...empty});}

export default function PayrollHoursPage(){const initial=initialPeriod();const[month,setMonth]=useState(initial.month);const[period,setPeriod]=useState(initial.period);const[location,setLocation]=useState('ALL');const[rows,setRows]=useState<Row[]>([]);const[summary,setSummary]=useState<Summary>(empty);const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[message,setMessage]=useState('');const range=useMemo(()=>dates(month,period),[month,period]);const loadSeq=useRef(0);
  const load=useCallback(async()=>{const seq=++loadSeq.current;setLoading(true);setMessage('');try{const response=await fetch(`/api/payroll-report?start=${range.start}&end=${range.end}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load payroll hours');if(seq===loadSeq.current){setRows(data.rows||[]);setSummary(data.summary||empty);}}catch(error:any){if(seq===loadSeq.current)setMessage(error.message);}finally{if(seq===loadSeq.current)setLoading(false);}},[range.start,range.end]);
  useEffect(()=>{load();},[load]);
  const locations=useMemo(()=>[...new Set(rows.flatMap(row=>row.locations))].sort(),[rows]);const visible=useMemo(()=>location==='ALL'?rows:rows.filter(row=>row.locations.includes(location)).map(row=>payrollLocationView(row,location)),[rows,location]);const visibleSummary=useMemo(()=>location==='ALL'?summary:summarize(visible),[location,summary,visible]);
  const sync=async()=>{setSyncing(true);setMessage('');try{const response=await fetch('/api/7shifts/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start:`${range.start}T00:00:00.000Z`,end:`${range.end}T23:59:59.999Z`,triggered_by:'payroll-hours',sync_wages:false})});const data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.error||'7shifts sync failed');await load();setMessage(`Updated ${data.synced?.punches||0} punches. Review checks before export.`);}catch(error:any){setMessage(error.message);}finally{setSyncing(false);}};
  const exportUrl=`/api/payroll-report/export?start=${range.start}&end=${range.end}${location==='ALL'?'':`&location=${encodeURIComponent(location)}`}`;
  return <main style={{background:'#090c10',minHeight:'100vh',color:'#e5e7eb',fontFamily:'Inter,sans-serif',padding:'22px 28px'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap',marginBottom:16}}><div><h1 style={{fontSize:23,margin:0,color:'#f9fafb'}}>Biweekly Payroll Hours</h1><p style={{fontSize:12,color:'#6b7280',margin:'5px 0 0'}}>Completed 7shifts punches · unpaid breaks deducted · combined multi-location rules</p></div><div style={{display:'flex',gap:8}}><button onClick={sync} disabled={syncing} style={{...control,color:'#22d3ee',cursor:syncing?'wait':'pointer'}}>{syncing?'Syncing…':'↻ Sync selected period'}</button><button onClick={()=>window.location.href=exportUrl} style={{...control,color:'#34d399',cursor:'pointer'}}>↓ Export payroll Excel</button></div></div>
  <section style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',background:'#131720',border:'1px solid rgba(255,255,255,.07)',borderRadius:10,padding:'11px 13px',marginBottom:12}}><label style={{fontSize:10,color:'#9ca3af'}}>Month <input type="month" value={month} onChange={event=>setMonth(event.target.value)} style={{...control,marginLeft:5}}/></label><label style={{fontSize:10,color:'#9ca3af'}}>Payroll period <select value={period} onChange={event=>setPeriod(event.target.value)} style={{...control,marginLeft:5}}><option value="1-15">1–15</option><option value="16-end">16–End</option></select></label><label style={{fontSize:10,color:'#9ca3af'}}>Location <select value={location} onChange={event=>setLocation(event.target.value)} style={{...control,marginLeft:5,maxWidth:230}}><option value="ALL">All locations — authoritative</option>{locations.map(item=><option key={item}>{item}</option>)}</select></label><span style={{fontSize:11,color:'#6b7280',marginLeft:'auto'}}>{range.start} → {range.end}</span></section>
  <div style={{padding:'9px 12px',borderRadius:8,background:'rgba(251,191,36,.08)',border:'1px solid rgba(251,191,36,.18)',color:'#fbbf24',fontSize:11,marginBottom:12}}>Payroll safeguard: cheque/cash limits are applied once to each employee’s combined hours across all locations. Location filtering never recalculates or duplicates their pay.</div>{message&&<div role="status" style={{fontSize:11,color:message.startsWith('Updated')?'#34d399':'#f87171',marginBottom:10}}>{message}</div>}
  <section style={{display:'grid',gridTemplateColumns:'repeat(6,minmax(120px,1fr))',gap:7,marginBottom:12}}>{[['Employees',visibleSummary.employees],['Gross clock',`${visibleSummary.gross_hours.toFixed(2)}h`],['All breaks',`${visibleSummary.break_hours.toFixed(2)}h`],['Payable',`${visibleSummary.payable_hours.toFixed(2)}h`],['Cheque',`${visibleSummary.cheque_hours.toFixed(2)}h`],['Cash',`${visibleSummary.cash_hours.toFixed(2)}h`]].map(([label,value])=><div key={label} style={{background:'#131720',border:'1px solid rgba(255,255,255,.07)',borderRadius:9,padding:'10px 12px'}}><div style={{fontSize:9,color:'#6b7280',textTransform:'uppercase'}}>{label}</div><div style={{fontSize:17,fontWeight:700,color:'#f9fafb',marginTop:3}}>{value}</div></div>)}</section>
  <div style={{background:'#131720',border:'1px solid rgba(255,255,255,.07)',borderRadius:11,overflow:'hidden'}}>{loading?<div style={{padding:50,textAlign:'center',color:'#6b7280'}}>Loading verified payroll hours…</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:11,minWidth:1450}}><thead><tr style={{background:'rgba(0,0,0,.25)'}}>{['Employee','Location(s)','Role(s)','Rate','Gross','Breaks','Unpaid Break','Payable','Rounded Up','Cheque Hrs','Cash Hrs','Cheque Pay','Cash Pay','Total Pay','Status'].map(label=><th key={label} style={{padding:'8px 9px',textAlign:['Employee','Location(s)','Role(s)','Status'].includes(label)?'left':'right',color:'#9ca3af',fontSize:9,textTransform:'uppercase',whiteSpace:'nowrap'}}>{label}</th>)}</tr></thead><tbody>{visible.map((row,index)=><tr key={row.employee_id} style={{borderTop:'1px solid rgba(255,255,255,.04)',background:row.status.includes('HOLD')?'rgba(248,113,113,.08)':row.cash_hours>0?'rgba(251,191,36,.045)':index%2?'rgba(255,255,255,.01)':'transparent'}}><td style={{padding:'8px 9px',fontWeight:600,color:'#f9fafb'}}>{row.employee_name}{row.wage<=0&&row.rule_type!=='SALARY_FIXED'&&<span style={{marginLeft:5,fontSize:8,color:'#f87171'}}>NO WAGE</span>}</td><td style={{padding:'8px 9px',color:'#9ca3af'}}>{row.locations.join('; ')}{row.locations.length>1&&<div style={{fontSize:9,color:'#22d3ee',marginTop:2}}>{row.locations.map(name=>`${name}: actual ${(row.location_gross_hours[name]||0).toFixed(2)}h / payable ${(row.location_hours[name]||0).toFixed(2)}h`).join(' · ')}</div>}</td><td style={{padding:'8px 9px',color:'#9ca3af'}}>{row.roles.join(', ')}</td><td style={{padding:'8px 9px',textAlign:'right'}}>{money(row.wage)}</td>{[row.gross_hours,row.break_hours,row.unpaid_break_hours,row.payable_hours,row.rounded_hours,row.cheque_hours,row.cash_hours].map((value,i)=><td key={i} style={{padding:'8px 9px',textAlign:'right',color:i===3?'#22d3ee':i===5?'#a78bfa':i===6?'#fbbf24':'#d1d5db',fontWeight:i>=3?600:400}}>{value.toFixed(2)}</td>)}<td style={{padding:'8px 9px',textAlign:'right',color:'#a78bfa'}}>{money(row.cheque_pay)}</td><td style={{padding:'8px 9px',textAlign:'right',color:'#fbbf24'}}>{money(row.cash_pay)}</td><td style={{padding:'8px 9px',textAlign:'right',color:'#34d399',fontWeight:700}}>{money(row.total_pay)}</td><td style={{padding:'8px 9px',color:row.status?'#fbbf24':'#4b5563'}} title={row.notes}>{row.status||'Standard'}</td></tr>)}</tbody></table></div>}</div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(7,minmax(110px,1fr))',gap:7,marginTop:10}}>{[['Total Gross',visibleSummary.gross_hours],['Total Breaks',visibleSummary.break_hours],['Total Unpaid Break',visible.reduce((sum,row)=>sum+row.unpaid_break_hours,0)],['Total Payable',visibleSummary.payable_hours],['Total Rounded',visibleSummary.rounded_hours],['Total Cheque Hrs',visibleSummary.cheque_hours],['Total Cash Hrs',visibleSummary.cash_hours]].map(([label,value])=><div key={label} style={{background:'#131720',border:'1px solid rgba(255,255,255,.08)',borderRadius:8,padding:'8px 10px',textAlign:'right'}}><div style={{fontSize:9,color:'#6b7280',textTransform:'uppercase'}}>{label}</div><div style={{fontSize:14,fontWeight:700,color:label==='Total Payable'?'#22d3ee':label==='Total Cheque Hrs'?'#a78bfa':label==='Total Cash Hrs'?'#fbbf24':'#e5e7eb',marginTop:2}}>{Number(value).toFixed(2)}h</div></div>)}</div>
  <div style={{display:'flex',justifyContent:'flex-end',gap:20,marginTop:10,fontSize:12}}><span style={{color:'#9ca3af'}}>Cheque Pay: <b style={{color:'#a78bfa'}}>{money(visibleSummary.cheque_pay)}</b></span><span style={{color:'#9ca3af'}}>Cash Pay: <b style={{color:'#fbbf24'}}>{money(visibleSummary.cash_pay)}</b></span><span style={{color:'#9ca3af'}}>Total Pay: <b style={{color:'#34d399'}}>{money(visibleSummary.total_pay)}</b></span></div></main>;
}
