import { NextRequest,NextResponse } from 'next/server';
import ExcelJS from 'exceljs';
import { getPayrollReport } from '@/lib/payroll-report-data';
import { payrollLocationView, summarizePayrollReport } from '@/lib/payroll-report';

const green='FF087866',light='FFD7F0EC',orange='FFFFE0B2',yellow='FFFFF176',red='FFFFCDD2';
function header(row:ExcelJS.Row){row.font={bold:true,color:{argb:'FFFFFFFF'}};row.fill={type:'pattern',pattern:'solid',fgColor:{argb:green}};row.alignment={vertical:'middle',wrapText:true};row.height=34;}
function addMerged(workbook:ExcelJS.Workbook,rows:any[],start:string,end:string){
  const sheet=workbook.addWorksheet('ALL (Merged)');sheet.mergeCells('A1:U1');sheet.getCell('A1').value=`ALL LOCATIONS MERGED — ${start} to ${end}`;sheet.getCell('A1').font={bold:true,size:15};
  sheet.mergeCells('A2:U2');sheet.getCell('A2').value='Payroll authority: completed 7shifts punches only. Payable hours deduct unpaid breaks; combined hours are rounded to the nearest quarter hour once per employee before cheque/cash rules.';sheet.getCell('A2').font={italic:true,color:{argb:'FF666666'}};
  const labels=['#','Employee','Location(s)','Role(s)','Rate ($/hr)','Gross Clock Hours','Break Hours (all)','Unpaid Break Hours','Payable Hours','Rounded Hours (0.25h)','Cheque Hours','Cash Hours','Cheque Pay ($)','Cash Pay ($)','Total Pay ($)','Status','Notes','Rule Type','Cheque Cap','Rule Value','Cash Rate'];
  sheet.addRow([]);const top=sheet.addRow(labels);header(top);
  rows.forEach((row,index)=>{const excelRow=sheet.addRow([index+1,row.employee_name,row.locations.join('; '),row.roles.join(', '),row.wage,row.gross_hours,row.break_hours,row.unpaid_break_hours,row.payable_hours,null,null,null,null,null,null,row.status,row.notes,row.rule_type,row.cheque_cap,row.rule_value,row.cash_wage]);const n=excelRow.number;
    excelRow.getCell(10).value={formula:`ROUND(I${n}*4,0)/4`,result:row.rounded_hours};
    excelRow.getCell(11).value={formula:`IF(OR(R${n}="CASH_ONLY",R${n}="HOLD_PAYROLL"),0,IF(R${n}="SALARY_FIXED",J${n},MIN(J${n},S${n})))`,result:row.cheque_hours};
    excelRow.getCell(12).value={formula:`IF(OR(R${n}="HOLD_PAYROLL",R${n}="SALARY_FIXED"),0,J${n}-K${n})`,result:row.cash_hours};
    excelRow.getCell(13).value={formula:`IF(R${n}="SALARY_FIXED",T${n},ROUND(K${n}*E${n},2))`,result:row.cheque_pay};
    excelRow.getCell(14).value={formula:`ROUND(L${n}*U${n},2)`,result:row.cash_pay};
    excelRow.getCell(15).value={formula:`M${n}+N${n}`,result:row.total_pay};
    if(row.status.includes('HOLD'))excelRow.fill={type:'pattern',pattern:'solid',fgColor:{argb:red}};else if(row.status.includes('CASH')||row.status.includes('Exception'))excelRow.fill={type:'pattern',pattern:'solid',fgColor:{argb:yellow}};else if(row.cash_hours>0)excelRow.fill={type:'pattern',pattern:'solid',fgColor:{argb:orange}};
  });
  const totalRow=sheet.addRow(['','TOTAL','','','',...Array(16).fill(null)]);const first=5,last=4+rows.length;totalRow.fill={type:'pattern',pattern:'solid',fgColor:{argb:light}};totalRow.font={bold:true};
  [6,7,8,9,10,11,12,13,14,15].forEach(column=>{totalRow.getCell(column).value={formula:`SUM(${sheet.getColumn(column).letter}${first}:${sheet.getColumn(column).letter}${last})`};});
  sheet.columns=[6,30,28,24,12,16,15,18,15,16,14,12,15,14,15,18,50,20,12,12,12].map(width=>({width}));sheet.views=[{state:'frozen',ySplit:4,xSplit:2}];sheet.autoFilter={from:'A4',to:'U4'};sheet.getColumn(5).numFmt='$0.00';for(let c=6;c<=12;c++)sheet.getColumn(c).numFmt='0.00';for(let c=13;c<=15;c++)sheet.getColumn(c).numFmt='$#,##0.00';for(let c=18;c<=21;c++)sheet.getColumn(c).hidden=true;
}
function safeName(value:string){return value.replace(/^Chiang Mai /,'').replace(/[\\/*?:\[\]]/g,'').slice(0,31)||'Location';}
function addLocation(workbook:ExcelJS.Workbook,location:string,rows:any[],start:string,end:string){const sheet=workbook.addWorksheet(safeName(location));sheet.mergeCells('A1:M1');sheet.getCell('A1').value=`${location} — ${start} to ${end}`;sheet.getCell('A1').font={bold:true,size:14};sheet.mergeCells('A2:M2');sheet.getCell('A2').value='Hours are shown for this location only. Cheque/cash hours and pay are allocated proportionally from the authoritative combined employee result on ALL (Merged).';sheet.getCell('A2').font={italic:true,color:{argb:'FF666666'}};sheet.addRow([]);const head=sheet.addRow(['#','Employee','Role(s)','Actual Hours','Break Hours','Payable Hours','Rounded 0.25h','Cheque Hours','Cash Hours','Cheque Pay','Cash Pay','Total Pay','Notes']);header(head);rows.forEach((row,index)=>{const local=payrollLocationView(row,location);sheet.addRow([index+1,row.employee_name,row.roles.join(', '),local.gross_hours,local.break_hours,local.payable_hours,local.rounded_hours,local.cheque_hours,local.cash_hours,local.cheque_pay,local.cash_pay,local.total_pay,row.locations.length>1?`Also worked: ${row.locations.filter((item:string)=>item!==location).join(', ')}`:row.notes]);});sheet.columns=[6,30,24,16,14,16,16,15,14,15,14,15,55].map(width=>({width}));sheet.views=[{state:'frozen',ySplit:4,xSplit:2}];sheet.autoFilter={from:'A4',to:'M4'};for(let c=4;c<=9;c++)sheet.getColumn(c).numFmt='0.00';for(let c=10;c<=12;c++)sheet.getColumn(c).numFmt='$#,##0.00';}

export async function GET(request:NextRequest){try{const params=request.nextUrl.searchParams;const start=params.get('start')||'';const end=params.get('end')||'';const selectedLocation=params.get('location')||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))return NextResponse.json({error:'Valid dates are required'},{status:400});const report=await getPayrollReport(start,end);const rows=selectedLocation?report.rows.filter(row=>row.locations.includes(selectedLocation)):report.rows;const workbook=new ExcelJS.Workbook();workbook.creator='CM Pay';workbook.created=new Date();addMerged(workbook,rows,start,end);const locations=selectedLocation?[selectedLocation]:[...new Set(rows.flatMap(row=>row.locations))].sort();locations.forEach(location=>addLocation(workbook,location,rows.filter(row=>row.locations.includes(location)),start,end));
  const exceptions=workbook.addWorksheet('Exception Actions');exceptions.columns=[{header:'Employee',width:30},{header:'Rule / Status',width:24},{header:'Action Applied',width:45},{header:'Notes',width:70}];header(exceptions.getRow(1));rows.filter(row=>row.status||row.notes).forEach(row=>exceptions.addRow([row.employee_name,row.status,`${row.cheque_hours.toFixed(2)} cheque / ${row.cash_hours.toFixed(2)} cash`,row.notes]));
  const checks=workbook.addWorksheet('Checks');checks.columns=[{width:34},{width:18},{width:20}];checks.addRow(['PAYROLL CHECKS','Value','Status']);header(checks.getRow(1));const summary=summarizePayrollReport(rows);const locationHours=rows.reduce((sum,row)=>sum+Object.values(row.location_hours).reduce((a,b)=>a+b,0),0);const missingWages=rows.filter(row=>row.wage<=0&&row.rule_type!=='SALARY_FIXED').length;checks.addRows([['Employee count',summary.employees,'INFO'],['Payable hours',summary.payable_hours,'INFO'],['Location hours reconciliation',Math.round((locationHours-summary.payable_hours)*100)/100,Math.abs(locationHours-summary.payable_hours)<.01?'PASS':'FAIL'],['Employees missing wage',missingWages,missingWages===0?'PASS':'FAIL'],['Gross - payable (unpaid breaks)',Math.round((summary.gross_hours-summary.payable_hours)*100)/100,'INFO'],['All recorded break hours',summary.break_hours,'INFO']]);checks.getColumn(2).numFmt='0.00';
  const buffer=await workbook.xlsx.writeBuffer();return new NextResponse(buffer as any,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="Payroll_${start}_${end}${selectedLocation?`_${safeName(selectedLocation)}`:''}.xlsx"`}});}catch(error:any){return NextResponse.json({error:error.message},{status:500});}}
